spring:
  rabbitmq:
    host: rabbitmq

server:
  port: 8060
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

eureka: 
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

feign:
  hystrix:
    enabled: true

zuul:
  ignoredServices: '*'
  routes:       
    sv-asr:
      path: /sa/**
      sensitiveHeaders:
    sv-qc:
      path: /sb/**
      sensitiveHeaders:
    sv-sre:
      path: /sre/**
      sensitiveHeaders:
    sv-qclient:
      path: /qclient/**
      sensitiveHeaders:
    sv-x:
      path: /sx/**
      sensitiveHeaders:
    
    sv-emotion:
      path: /sv-emotion/**
      sensitiveHeaders:     
    
    sv-tts:
      path: /sv-tts/**
      sensitiveHeaders: 

    smart-collection:
      path: /sv-sc/**
      sensitiveHeaders:
      
    tk:
      path: /getToken/**
      url: forward:/getToken

